- name: Prepare directories for PostgreSQL
  hosts: all
  become: yes
  tasks:
    - name: Ensure postgres user exists
      user:
        name: postgres
        state: present

    - name: Create /mnt/data/postgres directory
      file:
        path: /mnt/data/postgres
        state: directory
        mode: '0755'
        owner: postgres
        group: postgres


- name: Install AWX on Kubernetes using Helm
  hosts: master_node
  become: yes
  collections:
    - kubernetes.core
  vars:
    helm_repo: "https://ansible-community.github.io/awx-operator-helm/"
    helm_chart: "awx-operator"
    k8s_namespace: "awx"
    awx_cr: |
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
        namespace: awx
      spec:
        service_type: clusterip
        ingress_type: none
        postgres_storage_class: awx-projects-storage-class  # Specify the storage class for PostgreSQL
    pv_config: |
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: postgres-15-pv
        namespace: awx
      spec:
        capacity:
          storage: 10Gi
        accessModes:
          - ReadWriteOnce
        hostPath:
          path: /mnt/data/postgres  # Ensure this path exists on the node
        storageClassName: awx-projects-storage-class
    pvc_config: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-15-awx-postgres-15-0
        namespace: awx
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: awx-projects-storage-class

  tasks:
    - name: Ensure Python's pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install required Python libraries using apt
      apt:
        name:
          - python3-kubernetes
          - python3-openshift
        state: present

    - name: Download Helm GPG key using curl
      command: curl -fsSL https://baltocdn.com/helm/signing.asc -o /tmp/helm-signing.asc

    - name: Add Helm GPG key to apt
      apt_key:
        file: /tmp/helm-signing.asc
        state: present

    - name: Add Helm APT repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Helm
      apt:
        name: helm
        state: present

    - name: Add AWX Helm repository
      command: helm repo add awx-operator "{{ helm_repo }}"

    - name: Update Helm repositories
      command: helm repo update

    - name: Create AWX namespace if it doesn't exist
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"

    - name: Create Persistent Volume if it doesn't exist
      kubernetes.core.k8s:
        state: present
        definition: "{{ pv_config }}"

    - name: Create Persistent Volume Claim if it doesn't exist
      kubernetes.core.k8s:
        state: present
        definition: "{{ pvc_config }}"

    - name: Install AWX Operator using Helm
      command: helm install awx-operator awx-operator/"{{ helm_chart }}" --namespace "{{ k8s_namespace }}" --create-namespace

    - name: Deploy AWX using custom resource
      copy:
        content: "{{ awx_cr }}"
        dest: /tmp/awx-cr.yml

    - name: Apply AWX custom resource
      shell: kubectl apply -f /tmp/awx-cr.yml

    - name: Verify Kubernetes config permissions
      command: chmod 600 /root/.kube/config
      when: ansible_facts['user_id'] == 0  # Only run this when the user is root

    - name: Clean up temporary Helm GPG key
      file:
        path: /tmp/helm-signing.asc
        state: absent
