---
- hosts: all
  become: yes
  tasks:
    - name: Create Laravel Kubernetes deployment
      kubernetes:
        definition: "{{ lookup('file', 'kubernetes/manifests/laravel-deployment.yaml') }}"
    - name: Create Ingress resource for Laravel app
      kubernetes:
        definition: "{{ lookup('file', 'kubernetes/manifests/ingress.yaml') }}"
