apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
